### ISSUE TITLE
kotlin.UninitializedPropertyAccessException - lateinit property _context has not been initialized

### ISSUE THREAD

**Issue by AuroPick** [dengage-tech/dengage-react-sdk#7]
Hi We get this error in our react-native app

![image](https://github.com/dengage-tech/dengage-react-sdk/assets/53499802/b50fa532-cf6f-4207-8474-6ccc1e5113fb)

This error seems to occur when a notification is received

react-native: 0.71.7
dengage react-native: 0.6.0

**Comment by hasnainTanvir** [comment]
you can use the following lines in the build gradle of app   implementation 'com.github.dengage-tech:dengage-android-sdk:6.0.40.1'

**Comment by hasnainTanvir** [comment]
you can use the following lines in the build gradle of app   implementation 'com.github.dengage-tech:dengage-android-sdk:6.0.40.1'

**Comment by AuroPick** [comment]
Okay I will update the library on next release and will let you know.
