### ISSUE TITLE
React native supported versions

### ISSUE THREAD

**Issue by burakakyol** [dengage-tech/dengage-react-sdk#8]
Hi @hasnainTanvir , 

After upgrading our react native version from 0.66.5 to 0.71.12. We faced some unexpected behaviors in the application such as UI errors, and empty screens. Is there any example project that is implemented by react-native > 0.70?  Also, Is there a list to get supported react native versions by dEngage ? 

**Npm packages:**

```
"@dengage-tech/react-native-dengage": "0.6.1",
"react-native": "0.71.12",
```

**Android packages:**
```
    implementation ("com.github.dengage-tech:dengage-android-sdk:6.0.38.2"){
        exclude group: 'com.google.android.play', module:'core'
    }
```

```
    implementation(project(':dengage-tech_react-native-dengage')) {
        exclude group: 'com.google.android.play', module:'core'
    }
```

**build.gradle**
```
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24
        compileSdkVersion = 33
        targetSdkVersion = 33
        RNNKotlinVersion = "1.9.0"
        RNNKotlinStdlib = "kotlin-stdlib-jdk8"
```
...
```
classpath("com.android.tools.build:gradle:7.4.2")
classpath("com.google.gms:google-services:4.3.3")
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.0"
classpath 'io.fabric.tools:gradle:1.28.1' // Crashlytics
classpath("com.facebook.react:react-native-gradle-plugin")
```

**Comment by hasnainTanvir** [comment]
hi @burakakyol , actually the dengage library is compatible with every latest react native version , if you are facing blank screens , i don't think this is related to dengage

**Comment by burakakyol** [comment]
Just wanted to be sure whether there was a compatibility issue or not. So, as far as I understand, SDK works with every RN version. 

Thank you for your response.
